services:
  controllers:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #  args:
    #    - USER_UID=${USER_UID}
    #    - USER_GID=${USER_GID}
    image: compliant-controllers:rr-dev
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    working_dir: /controllers_ws
    network_mode: host
    ipc: host
    privileged: true
    entrypoint: ["/ros_entrypoint.sh"]
    command: >
      bash -c "
      source /opt/ros/humble/setup.bash &&
      source /controllers_ws/install/setup.bash &&
      ros2 launch compliant_controllers_demos fr3.launch.py
      "

    tty: true
    stdin_open: true
    init: true
    volumes:
      - ./:/controllers_ws/src/compliant_controllers
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
      ROS_DISTRO: humble
      ROS_DOMAIN_ID: 42
    cpuset: "20-27"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
