<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>compliant_controllers</name>
  <version>0.0.1</version>
  <description>Compliant controllers for ROS2 with message based plugin infrastructure.</description>
  <maintainer email="smihael@gmail.com">Mihael Simonic</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>controller_interface</depend>
  <depend>hardware_interface</depend>
  <depend>controller_manager</depend>
  <depend>joint_state_broadcaster</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>realtime_tools</depend>
  <depend>std_srvs</depend>
  <depend>std_msgs</depend>
  <depend>franka_msgs</depend>
  <depend>compliant_controllers_msgs</depend>
  <depend>ros2_control_robot_dynamics</depend>
  <depend>urdf</depend>
  <depend>sensor_msgs</depend>
  <depend>eigen</depend>
  <depend>pinocchio</depend>

  <test_depend>ament_cmake_gmock</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <pluginlib plugin="${prefix}/compliant_controllers.xml"/>
  </export>
</package>
